services:
  application:
    image: web-image:v1
    networks:
      - proxy

  nginx:
    image: nginx-basic-auth
    ports:
      - "8123:8123"
    depends_on:
      - application
    environment: 
      - PORT=8123
      - CLIENT_MAX_BODY_SIZE=1m
      - WORKER_PROCESSES=auto
      - BASIC_AUTH_USERNAME=username
      - BASIC_AUTH_PASSWORD=password
    networks:
      - proxy

networks:
  proxy:
    external: true